Repository eProsima/Fast-DDS-statistics-backend, pull requests merged in 2021-07, with the labels that each got.

#95 Call user callbacks when entities are undiscovered [11856]
  src/cpp/StatisticsBackendData.cpp
  src/cpp/StatisticsBackendData.hpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/database_queue.cpp
  src/cpp/database/database_queue.hpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  test/mock/StatisticsBackend/StatisticsBackendData.hpp
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseStatusTests.cpp
  test/unittest/DatabaseQueue/CMakeLists.txt
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/Resources/complex_dump.json
  test/unittest/Resources/empty_entities_dump.json
  test/unittest/Resources/old_complex_dump.json
  test/unittest/Resources/simple_dump.json
  test/unittest/Resources/simple_dump_no_process_participant_link.json
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
  test/unittest/StatisticsBackend/IsActiveTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/StatisticsParticipantListener/CMakeLists.txt
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
Labels: first-to-merge

#102 Set a descriptive name for discovered participants if none is given by the user [#11907]
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  test/unittest/StatisticsParticipantListener/CMakeLists.txt
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
Labels: first-to-merge

#108 Fix queue race condition [11966]
  src/cpp/subscriber/StatisticsParticipantListener.cpp
Labels: first-to-merge

#107 Issue: Entities does not turn back to live [11958]
  src/cpp/database/database.cpp
  src/cpp/database/entities.hpp
  test/unittest/Database/CMakeLists.txt
  test/unittest/Database/DatabaseStatusTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/IsActiveTests.cpp
Labels: first-to-merge

#104 locators notification [11918]
  include/fastdds_statistics_backend/listener/PhysicalListener.hpp
  src/cpp/StatisticsBackendData.cpp
  src/cpp/StatisticsBackendData.hpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/database_queue.hpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  test/mock/StatisticsBackend/StatisticsBackendData.hpp
  test/unittest/Database/DatabaseStatusTests.cpp
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
  test/unittest/StatisticsBackend/IsActiveTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
Labels: ready

#96 Minimal system test [11649]
  test/CMakeLists.txt
  test/dds/communication/CMakeLists.txt
  test/dds/communication/Host.hpp
  test/dds/communication/Monitor.cpp
  test/dds/communication/Publisher.cpp
  test/dds/communication/Subscriber.cpp
  test/dds/communication/example_type.xml
  test/dds/communication/simple_communication.py
Labels: first-to-merge

#116 Fix participant name
  src/cpp/StatisticsBackend.cpp
Labels: bug

#80 Metatraffic topic and endpoints [11706]
  include/fastdds_statistics_backend/types/JSONTags.h
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/entities.hpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  test/dds/communication/Monitor.cpp
  test/dds/communication/simple_communication.py
  test/unittest/Resources/complex_dump.json
  test/unittest/Resources/complex_dump_erased_domain_1.json
  test/unittest/Resources/database_dump.json
  test/unittest/Resources/empty_entities_dump.json
  test/unittest/Resources/old_complex_dump.json
  test/unittest/Resources/simple_dump.json
  test/unittest/Resources/simple_dump_no_process_participant_link.json
  test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
  test/unittest/StatisticsParticipantListener/CMakeLists.txt
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
Labels: first-to-merge

#113 Refactor network latency data [12033]
  docs/rst/statistics_backend/get_data.rst
  include/fastdds_statistics_backend/types/types.hpp
  src/cpp/StatisticsBackend.cpp
  src/cpp/database/data.cpp
  src/cpp/database/data.hpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/database_queue.cpp
  src/cpp/database/database_queue.hpp
  src/cpp/database/entities.cpp
  src/cpp/database/entities.hpp
  test/unittest/Database/CMakeLists.txt
  test/unittest/Database/DataTests.cpp
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseLoadInsertTests.cpp
  test/unittest/Database/DatabaseLoadTests.cpp
  test/unittest/Database/DatabaseTests.cpp
  test/unittest/DatabaseQueue/CMakeLists.txt
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/Resources/complex_dump.json
  test/unittest/Resources/complex_dump_erased_domain_1.json
  test/unittest/Resources/database_dump.json
  test/unittest/Resources/empty_entities_dump.json
  test/unittest/Resources/old_complex_dump.json
  test/unittest/Resources/simple_dump.json
  test/unittest/Resources/simple_dump_no_process_participant_link.json
  test/unittest/Resources/simple_dump_no_process_participant_link_erased_domain.json
  test/unittest/StatisticsBackend/BackendDumpTests.cpp
  test/unittest/StatisticsBackend/GetDataTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/StatisticsReaderListener/StatisticsReaderListenerTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
Labels: first-to-merge
