Repository eProsima/Fast-DDS-statistics-backend, pull requests merged in 2021-06, with the labels that each got.

#73 [11477] Windows revamping
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/common/gtest.cmake
  docs/conf.py
  include/fastdds_statistics_backend/exception/Exception.hpp
  include/fastdds_statistics_backend/types/EntityId.hpp
  src/cpp/CMakeLists.txt
  src/cpp/StatisticsBackend.cpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/database_queue.cpp
  src/cpp/database/database_queue.hpp
  src/cpp/detail/data_getters.hpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  src/cpp/subscriber/StatisticsReaderListener.cpp
  src/cpp/topic_types/types.cxx
  test/mock/database/database/database/database.hpp
  test/mock/dds/DomainParticipant/fastdds/dds/domain/DomainParticipant.hpp
  test/mock/dds/DomainParticipantFactory/fastdds/dds/domain/DomainParticipantFactory.hpp
  test/mock/dds/Publisher/fastdds/dds/publisher/Publisher.hpp
  test/mock/dds/Subscriber/fastdds/dds/subscriber/Subscriber.hpp
  test/mock/dds/TopicDescription/fastdds/dds/topic/TopicDescription.hpp
  test/unittest/CMakeLists.txt
  test/unittest/Database/CMakeLists.txt
  test/unittest/Database/DataTests.cpp
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseGetEntitiesTest.cpp
  test/unittest/Database/DatabaseLoadInsertTests.cpp
  test/unittest/Database/DatabaseLoadTests.cpp
  test/unittest/Database/DatabaseTests.cpp
  test/unittest/Database/SampleTests.cpp
  test/unittest/Database/resources/complex_dump.json
  test/unittest/Database/resources/simple_dump.json
  test/unittest/Database/resources/simple_dump_no_process_participant_link.json
  test/unittest/DatabaseQueue/CMakeLists.txt
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/EntityId/CMakeLists.txt
  test/unittest/EntityId/EntityIdTests.cpp
  test/unittest/QosSerializer/CMakeLists.txt
  test/unittest/QosSerializer/QosSerializerTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
  test/unittest/StatisticsBackend/GetDataTests.cpp
  test/unittest/StatisticsBackend/InitMonitorFactoryFailsTests.cpp
  test/unittest/StatisticsBackend/InitMonitorTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/StatisticsBackend/resources/database_dump.json
  test/unittest/StatisticsParticipantListener/CMakeLists.txt
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
  test/unittest/StatisticsReaderListener/CMakeLists.txt
  test/unittest/StatisticsReaderListener/StatisticsReaderListenerTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
  test/unittest/TestUtils/gtest_aux.hpp
  test/unittest/TrafficInjector/CMakeLists.txt
  test/unittest/TrafficInjector/TrafficInjectorTests.cpp
Labels: first-to-merge, high-priority

#86 Improve documentation of throwing methods [11820]
  docs/rst/exports/alias.include
  docs/rst/statistics_backend/get_data.rst
  docs/rst/statistics_backend/get_entities.rst
  docs/rst/statistics_backend/get_type.rst
  docs/rst/statistics_backend/init_monitor.rst
  docs/rst/statistics_backend/set_listeners.rst
  docs/rst/statistics_backend/stop_restart.rst
  include/fastdds_statistics_backend/StatisticsBackend.hpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/detail/data_getters.hpp
Labels: ready

#87 Bugfix/topics in different domain [11838]
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  test/unittest/StatisticsParticipantListener/CMakeLists.txt
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
Labels: ready

#89 get_data SAMPLE_DATAS implementation and tests [11816]
  src/cpp/database/database.hpp
  src/cpp/detail/data_getters.hpp
  test/unittest/StatisticsBackend/GetDataTests.cpp
  test/unittest/StatisticsBackend/resources/database_dump.json
Labels: first-to-merge, ready

#83 Discovery time tests and implementation [11816]
  src/cpp/detail/data_getters.hpp
  test/unittest/StatisticsBackend/GetDataTests.cpp
  test/unittest/StatisticsBackend/resources/database_dump.json
Labels: first-to-merge

#93 Entity alias [11864]
  include/fastdds_statistics_backend/StatisticsBackend.hpp
  include/fastdds_statistics_backend/types/JSONTags.h
  src/cpp/StatisticsBackend.cpp
  src/cpp/database/database.cpp
  src/cpp/database/entities.hpp
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseLoadInsertTests.cpp
  test/unittest/Database/DatabaseLoadTests.cpp
  test/unittest/Database/DatabaseTests.cpp
  test/unittest/Database/resources/complex_dump.json
  test/unittest/Database/resources/empty_entities_dump.json
  test/unittest/Database/resources/old_complex_dump.json
  test/unittest/Database/resources/simple_dump.json
  test/unittest/Database/resources/simple_dump_no_process_participant_link.json
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/StatisticsBackend/resources/database_dump.json
  test/unittest/TrafficInjector/CMakeLists.txt
  test/unittest/TrafficInjector/TrafficInjectorTests.cpp
  test/unittest/TrafficInjector/profile.xml
Labels: first-to-merge, ready

#84 StatisticsBackend::is_active() [11667]
  docs/rst/statistics_backend/is_active.rst
  src/cpp/StatisticsBackend.cpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/entities.hpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
  src/cpp/subscriber/StatisticsParticipantListener.hpp
  test/mock/database/database/database/database.hpp
  test/unittest/Database/CMakeLists.txt
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseLoadTests.cpp
  test/unittest/Database/DatabaseStatusTests.cpp
  test/unittest/Database/resources/complex_dump.json
  test/unittest/Database/resources/empty_entities_dump.json
  test/unittest/Database/resources/old_complex_dump.json
  test/unittest/Database/resources/simple_dump.json
  test/unittest/Database/resources/simple_dump_no_process_participant_link.json
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/InitMonitorTests.cpp
  test/unittest/StatisticsBackend/IsActiveTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
Labels: first-to-merge

#85 Database dump/load/reset [11744]
  docs/code/StatisticsBackendTests.cpp
  docs/code/dump_example.json
  docs/rst/api-reference/exception/exception_index.rst
  docs/rst/api-reference/exception/nodata.rst
  docs/rst/api-reference/exception/preconditionnotmet.rst
  docs/rst/exports/alias.include
  docs/rst/statistics_backend/dump_load.rst
  docs/rst/statistics_backend/statistics_backend.rst
  docs/rst/types/database_dumps.rst
  docs/rst/types/types_index.rst
  include/fastdds_statistics_backend/StatisticsBackend.hpp
  include/fastdds_statistics_backend/exception/Exception.hpp
  src/cpp/StatisticsBackend.cpp
  src/cpp/StatisticsBackendData.hpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/exception/Exception.cpp
  test/unittest/CMakeLists.txt
  test/unittest/Database/CMakeLists.txt
  test/unittest/Database/DatabaseDumpTests.cpp
  test/unittest/Database/DatabaseLoadTests.cpp
  test/unittest/Database/DatabaseStatusTests.cpp
  test/unittest/Resources/CMakeLists.txt
  test/unittest/Resources/complex_dump.json
  test/unittest/Resources/database_dump.json
  test/unittest/Resources/empty_dump.json
  test/unittest/Resources/empty_entities_dump.json
  test/unittest/Resources/old_complex_dump.json
  test/unittest/Resources/simple_dump.json
  test/unittest/Resources/simple_dump_no_process_participant_link.json
  test/unittest/StatisticsBackend/BackendDumpTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/GetDataTests.cpp
  test/unittest/StatisticsBackend/IsActiveTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
  test/unittest/TrafficInjector/CMakeLists.txt
Labels: first-to-merge, ready

#97 release 0.2.0
  CMakeLists.txt
  docs/rst/notes/notes.rst
  docs/rst/notes/previous_versions/v0.1.0.rst
  docs/rst/statistics_backend/get_data.rst
Labels: documentation

#75 set domain listener [11472]
  src/cpp/StatisticsBackend.cpp
  src/cpp/StatisticsBackendData.cpp
  src/cpp/database/database_queue.hpp
  test/unittest/Database/DatabaseGetEntitiesTest.cpp
  test/unittest/DatabaseQueue/DatabaseQueueTests.cpp
  test/unittest/StatisticsBackend/CMakeLists.txt
  test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
  test/unittest/TestUtils/DatabaseUtils.hpp
Labels: ready

#99 Use references on ranged for loops [11893]
  src/cpp/StatisticsBackend.cpp
  src/cpp/database/database.cpp
  src/cpp/database/database.hpp
  src/cpp/database/database_queue.cpp
  src/cpp/subscriber/QosSerializer.cpp
  src/cpp/subscriber/StatisticsParticipantListener.cpp
Labels: first-to-merge

#94 Add alive to get_info [11888]
  docs/code/datareader_info_example.json
  docs/code/datawriter_info_example.json
  docs/code/domain_info_example.json
  docs/code/host_info_example.json
  docs/code/locator_info_example.json
  docs/code/participant_info_example.json
  docs/code/process_info_example.json
  docs/code/topic_info_example.json
  docs/code/user_info_example.json
  docs/rst/statistics_backend/get_info.rst
  include/fastdds_statistics_backend/types/JSONTags.h
  src/cpp/StatisticsBackend.cpp
  test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
Labels: first-to-merge
